### ISSUE TITLE
Subscriptions: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by dpaola2** [uniiverse/apollo-tracing-ruby#10]
Hello!

Using the [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) gem and subscriptions. When a subscription response is empty, the Apollo library seems to assume a response, when there is no such response. So an exception is thrown.

Specifically, [this line](https://github.com/uniiverse/apollo-tracing-ruby/blob/v1.3.0/lib/apollo_tracing.rb#L66) seems to be the culprit.

See https://github.com/rmosolgo/graphql-ruby/issues/1362 for original discussion.

**Comment by exAspArk** [comment]
I'm closing the issue since it was fixed in `v1.7.14` https://github.com/rmosolgo/graphql-ruby/pull/1382. In case of exceptions, `graphql-ruby` will set the result value to `{}` instead of `nil`.
