### ISSUE TITLE
Array Arguments Bug

### ISSUE THREAD

**Issue by seannguyen** [uniiverse/apollo-tracing-ruby#8]
Apollo Proxy has a very annoying bug as stated in the following issues: 
https://github.com/apollographql/apollo-engine-js/issues/67
https://github.com/apollographql/apollo-engine-js/issues/53

Luckily, the issue has been fixed and release on apollo-engine-js side at version `2017.11-84-gb299b9188`. Can we update our dependency with that fixed version and release a new version apollo-tracing-ruby.

We're looking forward to have that fix reflect here.
Cheers,

**Comment by seannguyen** [comment]
Anw, I just sent this PR 
https://github.com/uniiverse/apollo-tracing-ruby/pull/9
Have a look and see if this make sense :D

**Comment by exAspArk** [comment]
Oh, nice! Thank you, I'll take a look soon.

We were just discussing adding an array of enums as an argument to our schema. Thankfully, we haven't faced the issue yet 😂

**Comment by exAspArk** [comment]
By the time when I was reading the Engine Proxy changelog yesterday, my colleagues released some GraphQL changes in our schema with the list of enums as an argument 😂 Will release a new version with the updated Proxy soon.

**Comment by seannguyen** [comment]
Thank guys
